### ISSUE TITLE
dry run

### ISSUE THREAD

**Issue by Maio-msdos** [x13a/Sentry#17]
Device: pixel 4a
OS: Android 13 graphene os
Thanks :)

**Comment by x13a** [comment]
![Screenshot_1661902437](https://user-images.githubusercontent.com/53379023/187561696-cdfdc42e-b579-48ae-b5a9-6ea33007a02e.png)

**Comment by x13a** [comment]
Have to add, that this notification is managed by Android. When you check _"Show X attempts left"_, Sentry will not handle checking for how many attempts left and show you a notification, but will set it via admin API. After that Android will rule it. GrapheneOS may remove this warning from the sources, I do not know. On the screenshot Android 13 in emulator with _"Max failed password attempts"_ set to 5 and _"Show X attempts left"_ checked.

**Comment by Maio-msdos** [comment]
Hmm okay that might be the case, the notification isn't the root issue it's more that it's hard to test if the app is working without actually wiping your device? Any chance of some kind of dry run mode? Perhaps when in dry run mode you get a notification in app when you would of triggered a wipe :) thanks

**Comment by x13a** [comment]
Maybe someday

**Comment by x13a** [comment]
Closing for now. Maybe will change my mind.
