### ISSUE TITLE
erase all data?

### ISSUE THREAD

**Issue by citizenserious** [x13a/Sentry#3]
When i activate this app, my phone shows me a warning to be erased if there are to many wrong password. I do not understand that. I don't want another person to be able to erase my entire phone, just by typing the wrong passwords. I thought this is to protect against attacks over USB? I use Wasted in parallel to manually and / or remotely wipe all my data. I am confused. Thanks for the help (:

**Comment by x13a** [comment]
This app is to enforce security policies. There is a slider with "maximum
failed password attempts". If it is set to zero (0), than your device will
not be wiped trying to unlock it.

**Comment by x13a** [comment]
Closing on inactivity

**Comment by marek22k** [comment]
For my understanding: In which cases is the device reset?

It is not reset if 0 is set?

**Comment by x13a** [comment]
> In which cases is the device reset?

if you set to 1 or more and enter the wrong password X times

> It is not reset if 0 is set?

yes
