### ISSUE TITLE
Prevent reboot, shutdown, wifi settings etc

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Sentry#4]
Could you prevent this action ?

- Shutdown
- Reboot
- Change the wifi settings
- Switching to airplane mode

Only if we are connected ?

N.b under grapheneos the usb is already protected so we can't touch the security policy with Sentry
So I don't know if with Sentry and grapheneos if we can touch the security policy

**Comment by x13a** [comment]
I do not think that shutdown and reboot can be prevented without low level
modifications. Changing WiFi settings and switching airplane mode can be
prevented simply by removing them from Tiles. If GrapheneOS already has USB
protection, use built in functionality. You can use Sentry to limit maximum
failed password attempts, if it is not implemented in GrapheneOS too.

**Comment by x13a** [comment]
Closing on inactivity
