### ISSUE TITLE
Force airplane mode ?

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Sentry#6]
Is it possible to force the airplane mode all the time with android 12/13?

the idea is to let the base band and the gps be disabled all the time.

Nb: even if it means to put the application in root

ps I tried to find a solution to remove the baseband from android but it creates errors, I'm looking for an idea without breaking everything how to force the baseband and gps to be always off.

**Comment by x13a** [comment]
You can enable airplane mode in settings and turn GPS off too. Will a device be visible to radio stations with it? I do not know. Anyway it is not in the scope of this app.

**Comment by xyz-nobody** [comment]
thk

**Comment by x13a** [comment]
Closing
